"""Deterministic corrected regulatory document generator service.

Produces a NEW in-memory byte stream from the retained original source document
bytes without ever mutating or modifying the original source document.

CRITICAL SAFETY & GOVERNANCE CONSTRAINTS:
- NEVER overwrites or mutates original source bytes in candidate store.
- Strictly enforces final human approval gate (approval_confirmation=True).
- Strictly rejects generation if any unresolved PENDING occurrences remain.
- Modifies ONLY confirmed occurrences (and confirmed primary changes).
- Leaves EXCLUDED occurrences 100% unaltered.
- Enforces unambiguous target resolution: zero matches or multiple ambiguous
  matches immediately fail generation.
- Operates transactionally in memory: returns no artifact if any target fails.
- Preserves document formatting and structure (run-level formatting for DOCX,
  UTF-8 encoding for TXT).
- Rejects input-only formats (PDF, legacy binary .doc) cleanly.
"""

from dataclasses import dataclass
import hashlib
import io
import logging
from pathlib import Path
import re
from typing import Any, List, Optional, Tuple

from pydantic import BaseModel, Field

from app.models.document_change import (
    ApprovedChangeReport,
    ProposedChange,
    RelatedOccurrence,
)
from app.services.candidate_store import (
    IngestedDocumentCandidateStore,
    get_candidate_store,
)

logger = logging.getLogger("corrected_document_generator")


class CorrectedDocumentError(Exception):
    """Base exception for corrected document generation errors."""
    pass


class UnsupportedFormatError(CorrectedDocumentError, ValueError):
    """Raised when document format is unsupported or input-only (e.g., PDF or legacy binary DOC)."""
    pass


class UnapprovedReportError(CorrectedDocumentError, ValueError):
    """Raised when report or change proposals have not received final human regulatory approval."""
    pass


class UnresolvedOccurrencesError(CorrectedDocumentError, ValueError):
    """Raised when unresolved PENDING occurrences exist."""
    pass


class TargetResolutionError(CorrectedDocumentError, ValueError):
    """Raised when target text has zero matches or multiple ambiguous matches."""
    pass


class CorrectedDocumentResult(BaseModel):
    """Artifact metadata and byte payload for a generated corrected regulatory document."""

    document_id: str = Field(..., description="Source regulatory document identifier")
    original_filename: str = Field(..., description="Original uploaded filename")
    output_filename: str = Field(..., description="Derived output filename")
    input_format: str = Field(..., description="Input format (e.g., 'docx', 'txt')")
    output_format: str = Field(..., description="Output format (e.g., 'docx', 'txt')")
    corrected_bytes: bytes = Field(..., description="New in-memory corrected document bytes")
    size_bytes: int = Field(..., description="Byte length of corrected document")
    sha256_hash: str = Field(..., description="SHA-256 hash of the corrected document bytes")

    @property
    def size(self) -> int:
        return self.size_bytes


@dataclass
class ModificationTarget:
    """Internal representation of a validated modification target."""
    source_text: str
    replacement_text: str
    section: Optional[str] = None
    location: Optional[str] = None
    occurrence_id: Optional[str] = None
    proposal_id: Optional[str] = None


class CorrectedDocumentGenerator:
    """Deterministic in-memory generator for corrected regulatory documents."""

    def __init__(
        self,
        candidate_store: Optional[IngestedDocumentCandidateStore] = None,
    ) -> None:
        self.candidate_store = candidate_store or get_candidate_store()

    def generate_corrected_document(
        self,
        report: Optional[ApprovedChangeReport] = None,
        document_id: Optional[str] = None,
        proposals: Optional[List[ProposedChange]] = None,
        output_filename: Optional[str] = None,
        approval_confirmation: Optional[bool] = None,
    ) -> CorrectedDocumentResult:
        """Generate a new corrected document from retained source bytes.

        Args:
            report: Authorized ApprovedChangeReport.
            document_id: Optional source document ID override.
            proposals: Optional list of approved ProposedChange objects.
            output_filename: Optional explicit output filename.
            approval_confirmation: Optional approval confirmation override if passing proposals directly.

        Returns:
            CorrectedDocumentResult with newly generated bytes and SHA-256 hash.

        Raises:
            UnapprovedReportError: If report or proposals lack final human approval confirmation.
            UnresolvedOccurrencesError: If any unresolved PENDING occurrences exist.
            UnsupportedFormatError: If source document is PDF, legacy DOC, or unsupported.
            TargetResolutionError: If any target has zero matches or multiple ambiguous matches.
            ValueError: If source document is missing or invalid.
        """
        # 1. Resolve authoritative document_id and proposals
        eff_doc_id = document_id or (report.document_id if report else None)
        if not eff_doc_id:
            raise ValueError("Document correction rejected: document_id is missing and could not be determined.")

        eff_proposals: List[ProposedChange] = []
        if report is not None:
            # Enforce report-level approval confirmation gate
            if not report.approval_confirmation:
                raise UnapprovedReportError(
                    "Document correction rejected: Change report has not received explicit human approval confirmation "
                    "(approval_confirmation=true)."
                )
            if not report.author_approver or not report.author_approver.strip():
                raise UnapprovedReportError(
                    "Document correction rejected: Valid human regulatory approver identity is required."
                )
            eff_proposals = list(report.changes or [])
        elif proposals is not None:
            # Enforce direct proposal approval confirmation gate
            is_confirmed = approval_confirmation is True or all(
                getattr(p, "status", None) == "APPROVED" for p in proposals
            )
            if not is_confirmed:
                raise UnapprovedReportError(
                    "Document correction rejected: Change proposals have not received final human approval."
                )
            eff_proposals = list(proposals)
        else:
            raise ValueError("Document correction rejected: Either 'report' or 'proposals' must be provided.")

        if not eff_proposals:
            raise ValueError("Document correction rejected: No change proposals available for correction generation.")

        # 2. Strict occurrence safety checks
        for prop in eff_proposals:
            for occ in prop.related_occurrences:
                if occ.status == "PENDING":
                    raise UnresolvedOccurrencesError(
                        f"Unresolved PENDING occurrence '{occ.occurrence_id}' detected in proposal '{prop.change_id}'. "
                        f"All occurrences must be explicitly reviewed (CONFIRMED or EXCLUDED) before corrected document generation."
                    )

        # 3. Retrieve retained original source document
        source_doc = self.candidate_store.get_source_document(eff_doc_id)
        if source_doc is None:
            raise ValueError(f"Source document '{eff_doc_id}' not found in candidate store.")

        orig_bytes = bytes(source_doc.source_bytes)
        if not orig_bytes:
            raise ValueError(f"Source document '{eff_doc_id}' contains empty source bytes.")

        eff_format = (source_doc.file_format or "").strip().lower().lstrip(".")
        if not eff_format and "." in source_doc.filename:
            eff_format = Path(source_doc.filename).suffix.strip().lower().lstrip(".")

        # 4. Check supported formats & reject input-only formats
        if eff_format == "pdf":
            raise UnsupportedFormatError(
                "PDF format is input-only; in-place PDF document correction is not supported."
            )
        if eff_format == "doc":
            raise UnsupportedFormatError(
                "Legacy DOC (.doc) format is input-only; direct binary .doc modification is not supported "
                "without external dependencies. Please use DOCX."
            )
        if eff_format not in ("docx", "txt", "text", "md"):
            raise UnsupportedFormatError(
                f"Unsupported format '{eff_format}' for corrected document generation. Supported formats: DOCX, TXT."
            )

        # 5. Collect modification targets
        targets: List[ModificationTarget] = []
        for prop in eff_proposals:
            if prop.related_occurrences:
                # If proposal has related occurrences, process CONFIRMED occurrences
                for occ in prop.related_occurrences:
                    if occ.status == "CONFIRMED":
                        # Authoritative replacement text comes from the parent ProposedChange
                        rep_text = prop.proposed_text
                        src_text = (occ.matched_text or occ.current_text or "").strip()
                        if not src_text:
                            raise ValueError(f"Occurrence '{occ.occurrence_id}' has empty source text.")
                        targets.append(
                            ModificationTarget(
                                source_text=src_text,
                                replacement_text=rep_text,
                                section=occ.section,
                                location=occ.location,
                                occurrence_id=occ.occurrence_id,
                                proposal_id=prop.change_id,
                            )
                        )
                    # EXCLUDED occurrences are intentionally skipped (remain untouched)
            else:
                # No related occurrences on this proposal: the primary change is the modification target
                if prop.original_text and prop.proposed_text and prop.original_text != prop.proposed_text:
                    targets.append(
                        ModificationTarget(
                            source_text=prop.original_text.strip(),
                            replacement_text=prop.proposed_text,
                            section=prop.section,
                            occurrence_id=prop.change_id,
                            proposal_id=prop.change_id,
                        )
                    )

        # 6. Generate NEW corrected byte stream transactionally
        if eff_format in ("txt", "text", "md"):
            corrected_bytes = self._generate_corrected_txt(orig_bytes, targets)
            out_fmt = "txt" if eff_format in ("txt", "text") else "md"
        elif eff_format == "docx":
            corrected_bytes = self._generate_corrected_docx(orig_bytes, targets)
            out_fmt = "docx"
        else:
            raise UnsupportedFormatError(f"Unsupported format '{eff_format}'.")

        # 7. Resolve output filename
        if output_filename and output_filename.strip():
            final_out_fn = output_filename.strip()
        else:
            stem = Path(source_doc.filename).stem
            ext = Path(source_doc.filename).suffix or f".{out_fmt}"
            final_out_fn = f"Corrected_{stem}{ext}"

        # 8. Compute artifact metadata and SHA-256 hash
        sha256 = hashlib.sha256(corrected_bytes).hexdigest()

        return CorrectedDocumentResult(
            document_id=eff_doc_id,
            original_filename=source_doc.filename,
            output_filename=final_out_fn,
            input_format=eff_format,
            output_format=out_fmt,
            corrected_bytes=corrected_bytes,
            size_bytes=len(corrected_bytes),
            sha256_hash=sha256,
        )

    def _generate_corrected_txt(
        self,
        source_bytes: bytes,
        targets: List[ModificationTarget],
    ) -> bytes:
        """Deterministically apply target replacements to plain text content."""
        content = source_bytes.decode("utf-8")

        if not targets:
            return source_bytes

        # Phase 1: Validate and resolve all targets to exact unique character spans (start, end)
        resolved_spans: List[Tuple[int, int, str, ModificationTarget]] = []

        for target in targets:
            src = target.source_text
            span: Optional[Tuple[int, int]] = None

            # Try section-bounded search if section context is present
            if target.section:
                sec_bounds = self._find_txt_section_bounds(content, target.section)
                if sec_bounds:
                    sec_start, sec_end = sec_bounds
                    sec_text = content[sec_start:sec_end]
                    sec_matches = [sec_start + m.start() for m in re.finditer(re.escape(src), sec_text)]
                    if len(sec_matches) == 1:
                        span = (sec_matches[0], sec_matches[0] + len(src))
                    elif len(sec_matches) > 1:
                        raise TargetResolutionError(
                            f"Multiple ambiguous matches ({len(sec_matches)}) found for occurrence '{target.occurrence_id}' "
                            f"in section '{target.section}'. Target text: '{src}'"
                        )

            # Fall back to document-wide matching if section search yielded no span
            if span is None:
                doc_matches = [m.start() for m in re.finditer(re.escape(src), content)]
                if len(doc_matches) == 0:
                    raise TargetResolutionError(
                        f"Zero matches found for occurrence '{target.occurrence_id}' in document. "
                        f"Expected target text: '{src}'"
                    )
                elif len(doc_matches) > 1:
                    raise TargetResolutionError(
                        f"Multiple ambiguous matches ({len(doc_matches)}) found for occurrence '{target.occurrence_id}' "
                        f"in document. Target text: '{src}'"
                    )
                span = (doc_matches[0], doc_matches[0] + len(src))

            resolved_spans.append((span[0], span[1], target.replacement_text, target))

        # Check for overlapping spans
        sorted_spans = sorted(resolved_spans, key=lambda s: s[0])
        for i in range(len(sorted_spans) - 1):
            if sorted_spans[i][1] > sorted_spans[i + 1][0]:
                raise TargetResolutionError(
                    f"Conflicting overlapping occurrence targets detected: "
                    f"'{sorted_spans[i][3].occurrence_id}' and '{sorted_spans[i+1][3].occurrence_id}'."
                )

        # Phase 2: Apply replacements in reverse order of start index to avoid offset shifting
        sorted_reverse = sorted(resolved_spans, key=lambda s: s[0], reverse=True)
        corrected_content = content
        for start, end, rep, _ in sorted_reverse:
            corrected_content = corrected_content[:start] + rep + corrected_content[end:]

        return corrected_content.encode("utf-8")

    def _find_txt_section_bounds(self, content: str, section_name: str) -> Optional[Tuple[int, int]]:
        """Find the start and end character offsets of a named section in plain text."""
        clean_sec = section_name.strip()
        pattern = rf"(?im)^\s*(?:[0-9]+\s+)?(?:#+\s*)?{re.escape(clean_sec)}\b.*$"
        match = re.search(pattern, content)
        if not match:
            return None

        sec_start = match.end()
        # Find subsequent section header
        next_heading_pattern = r"(?m)^\s*(?:[0-9]+\s+)?(?:#+\s*|[A-Z][A-Z0-9\s,/-]{3,}\b.*$)"
        rest = content[sec_start:]
        next_match = re.search(next_heading_pattern, rest)
        sec_end = sec_start + next_match.start() if next_match else len(content)
        return (sec_start, sec_end)

    def _generate_corrected_docx(
        self,
        source_bytes: bytes,
        targets: List[ModificationTarget],
    ) -> bytes:
        """Deterministically apply target replacements to DOCX content preserving runs/formatting."""
        import docx

        doc = docx.Document(io.BytesIO(source_bytes))

        if not targets:
            out_buf = io.BytesIO()
            doc.save(out_buf)
            return out_buf.getvalue()

        # Collect all paragraphs from body and table cells with section context
        all_paras = self._collect_docx_paragraphs(doc)

        # Phase 1: Validate and resolve all targets to specific paragraph elements
        resolutions: List[Tuple[Any, ModificationTarget]] = []

        for target in targets:
            src = target.source_text
            matching_paras = []
            for p, sec_name in all_paras:
                if src in p.text:
                    cnt = p.text.count(src)
                    if cnt > 1:
                        raise TargetResolutionError(
                            f"Multiple ambiguous matches ({cnt}) found for occurrence '{target.occurrence_id}' "
                            f"within a single paragraph: '{p.text[:60]}...'"
                        )
                    matching_paras.append((p, sec_name))

            if len(matching_paras) == 0:
                raise TargetResolutionError(
                    f"Zero matches found for occurrence '{target.occurrence_id}' in DOCX document. "
                    f"Expected target text: '{src}'"
                )
            elif len(matching_paras) == 1:
                resolutions.append((matching_paras[0][0], target))
            else:
                # Multiple paragraphs contain src. Attempt disambiguation using target.section
                disambiguated = []
                if target.section:
                    t_sec_lower = target.section.strip().lower()
                    for p, sec_name in matching_paras:
                        if sec_name and (t_sec_lower in sec_name.lower() or sec_name.lower() in t_sec_lower):
                            disambiguated.append((p, sec_name))

                if len(disambiguated) == 1:
                    resolutions.append((disambiguated[0][0], target))
                else:
                    raise TargetResolutionError(
                        f"Multiple ambiguous matches ({len(matching_paras)}) found for occurrence '{target.occurrence_id}' "
                        f"in DOCX document. Target text: '{src}'"
                    )

        # Phase 2: Apply targeted replacements preserving run formatting
        for p, target in resolutions:
            self._replace_in_docx_paragraph(p, target.source_text, target.replacement_text)

        out_buf = io.BytesIO()
        doc.save(out_buf)
        return out_buf.getvalue()

    def _collect_docx_paragraphs(self, doc: Any) -> List[Tuple[Any, Optional[str]]]:
        """Collect all paragraphs from body and table cells with tracked section context."""
        results: List[Tuple[Any, Optional[str]]] = []
        current_section: Optional[str] = None

        # 1. Document body paragraphs
        for p in doc.paragraphs:
            txt = p.text.strip()
            if p.style and hasattr(p.style, "name") and ("heading" in p.style.name.lower() or "title" in p.style.name.lower()):
                current_section = txt
            elif txt.isupper() and len(txt) > 3 and "\n" not in txt:
                current_section = txt
            results.append((p, current_section))

        # 2. Table cell paragraphs
        for tbl in doc.tables:
            for row in tbl.rows:
                for cell in row.cells:
                    for p in cell.paragraphs:
                        results.append((p, current_section))

        return results

    def _replace_in_docx_paragraph(self, paragraph: Any, source_text: str, replacement_text: str) -> None:
        """Targeted replacement within a DOCX paragraph preserving run-level formatting."""
        # 1. Check if source_text is contained entirely within a single run
        for run in paragraph.runs:
            if source_text in run.text:
                run.text = run.text.replace(source_text, replacement_text, 1)
                return

        # 2. Multi-run replacement
        full_text = paragraph.text
        if source_text not in full_text:
            return

        start_idx = full_text.find(source_text)
        end_idx = start_idx + len(source_text)

        run_spans = []
        curr = 0
        for run in paragraph.runs:
            r_len = len(run.text)
            run_spans.append((curr, curr + r_len, run))
            curr += r_len

        overlapping = [span for span in run_spans if span[0] < end_idx and span[1] > start_idx]
        if not overlapping:
            paragraph.text = full_text.replace(source_text, replacement_text, 1)
            return

        first_start, _, first_run = overlapping[0]
        last_start, _, last_run = overlapping[-1]

        if len(overlapping) == 1:
            prefix = first_run.text[:start_idx - first_start]
            suffix = first_run.text[end_idx - first_start:]
            first_run.text = prefix + replacement_text + suffix
        else:
            prefix = first_run.text[:start_idx - first_start]
            first_run.text = prefix + replacement_text
            for _, _, mid_run in overlapping[1:-1]:
                mid_run.text = ""
            suffix = last_run.text[end_idx - last_start:]
            last_run.text = suffix
